### ISSUE TITLE
Unable to think of an issue

### ISSUE THREAD

**Issue by DavidAnderson102** [mixmixmix/safari_test_repo#18]
I'm currently unable to think of an issue.  @mixmixmix , would you be able to forward me some code for a previous issue you made, ideally within the next few days?

**Comment by DavidAnderson102** [comment]
- [ ] Send issue idea
- [ ] Submit issue
- [ ] Solve issue

**Comment by mixmixmix** [comment]
Hi David, take a look at that:
https://github.com/mixmixmix/safari_test_repo/issues/16
